title: Homepage
description: Scribbles/Notes
url: https://pjrigali.github.io/
remote_theme: just-the-docs/just-the-docs
enable_copy_code_button: true
plugins:
- jekyll-remote-theme
- jekyll-default-layout